<?php

namespace TvShowManagerBundle\Repository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id int
     * @return mixed
     * Get one Episode by Id
     */
    public function myFindOneById($id){
        $qb = $this->createQueryBuilder('e');
        $qb->select('e')
            ->where('e.id = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()->getSingleResult();
    }
}
