<?php

namespace TvShowManagerBundle\Repository;

/**
 * TvShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvShowRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get all TvShow with his episodes
     * @return array
     */
    public function myFindAll(){
        // Ici l'alias 't' représente l'entité 'TvShow'
        $qb = $this->createQueryBuilder('t');
        // On select toute l'entité, du coup, on récupérera tous les champs de l'entité TvShow
        $qb->select('t')
            // On join l'entité episode, ce qui nous permet de récupérer tous les épisodes lié à nos TvShow
            ->join('t.episodes', 'e')
            // On select également tous les épisodes de chaque TvShow
            ->addSelect('e');

        // On consctruit la requête par rapport aux éléments défini en amont
        $query = $qb->getQuery();

        // Execution de la requête et récupuration des résultats
        $result = $query->getResult();

        // Renvoie des résultats
        return $result;
    }

    /**
     * Get one TvShow by id and his episodes
     * @return mixed
     */
    public function myFindOneById($id){
        $qb = $this->createQueryBuilder('t');
        $qb->select('t')
            ->where('t.id = :id')
            ->join('t.episodes', 'e')
            ->addSelect('e')
            ->setParameter('id', $id);

        return $qb->getQuery()->getSingleResult();
    }
}
