tv_show_manager_homepage:
    path:     /
    defaults: { _controller: TvShowManagerBundle:Default:index }

#Chargement des routes défini dans src/TvShowManagerBundle/Resources/config/routing/tvShow.yml en préfixant tous les path avec 'tvShow'
tvShow_route:
    prefix: /tvshow
    resource: '@TvShowManagerBundle/Resources/config/routing/tvShow.yml'

#Chargement des routes défini dans src/TvShowManagerBundle/Resources/config/routing/episode.yml en préfixant tous les path avec 'episode'
episode_route:
    prefix: /episode
    resource: '@TvShowManagerBundle/Resources/config/routing/episode.yml'